### ISSUE TITLE
Guides on GitHub are not easy to follow

### ISSUE THREAD

**Issue by robertmcnees** [spring-guides/getting-started-guides#162]
Due to security concerns, [Asciidoc include functionality](https://docs.asciidoctor.org/asciidoc/latest/directives/include/) is not rendered on GitHub. The reasons are detailed in this [GitHub issue](https://github.com/github/markup/issues/1095). Because the Spring getting started guides make heavy use of include functionality, the reader will see empty blocks of content if they are consuming the `README.md` directly from the GitHub page.

For example, the user may see this when visiting the GitHub page:

![image](https://github.com/spring-guides/getting-started-guides/assets/86265089/b868f135-87b1-430b-8024-d49a6a70ba95)

But this when visiting the same guide on spring.io:

![image](https://github.com/spring-guides/getting-started-guides/assets/86265089/398eab48-49c6-4293-a475-0be5858cc7a7)

**Comment by robertmcnees** [comment]
A possible solution is to use [Asciidoc Reducer](https://github.com/asciidoctor/asciidoctor-reducer) with the `allow-uri-read` option. The GitHub Action could run each time the README.adoc file is changed. The action may look something like:

```
jobs:
  build:
    runs-on: ubuntu-latest
        # checkout code

      - name: Install Asciidoctor Reducer
        run: sudo gem install asciidoctor-reducer
      - name: Reduce README
        run: asciidoctor-reducer -a allow-uri-read -o README-reduced.adoc README.adoc

        # commit and push README-reduced.adoc
```

The output of this would be a new `README-reduced.adoc` file that would show the included content from `README.adoc`.

This would require coordination with [guides renderer](https://github.com/spring-io/guides-renderer). The guides renderer would need to look for a file other than `README.adoc` to generate content, or GitHub would need to look for a file other than `README.adoc` to display by default.
